apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc # kubernets cluster svc명
  project: default # argocd Project
  source: # git
    path: guestbook
    repoURL: git@github.com:<Github Profile명>/service-repository.git
    targetRevision: HEAD
  syncPolicy: # 자동화된 gitops 관리
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true