apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: test.extension.example.com
spec:
  group: extension.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            size:
              type: integer
  scope: Namespaced
  names:
    plural: test
    singular: test
    kind: test