---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2a
spec:
  securityGroups: 
    - sg-0f8d38989239afcfe
  subnet: subnet-05df6ebe0080be138
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2c
spec:
  securityGroups: 
    - sg-0f8d38989239afcfe
  subnet: subnet-00c4b565d5018f63e